FROM ubuntu:latest
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:
RUN mkdir /root/inputfiles
RUN mkdir /root/scripts
RUN mkdir /root/serverscripts
RUN mkdir /root/clientscripts
COPY ./inputfiles /root/inputfiles
COPY ./scripts /root/scripts
COPY ./serverscripts /root/serverscripts
COPY ./clientscripts /root/clientiscripts
RUN apt update  && apt-get install -y python3 libpq-dev python-dev-is-python3 python3-psycopg2 net-tools vim 
